name: .NET Core Build

on:
  workflow_dispatch:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.201
      - name: Restore Dependencies
        run: dotnet restore --force
      - name: Depenceny Graph
        run: dotnet list package --include-transitive || true 
      - name: Build
        run: dotnet build --configuration Release --no-restore
